feat: add UI template for maintenance
Roman15122022/AutoCheckUp pull request #32
Opened 2024-11-26 21:15 UTC by YaroslavOkrema

![image](https://github.com/user-attachments/assets/d870fa38-43d5-4797-894b-bdb3f8292412)

2024-11-26 21:18 UTC, Roman15122022 requested changes
Use shadcn inputs and btns

And try to use all screen area

2024-11-26 21:20 UTC, Roman15122022 requested changes

2024-11-26 21:20 UTC, Roman15122022 commented on src/pages/ServiceMaintenance/index.tsx
> +                <h1>Service Date</h1>
use locale

2024-11-26 21:20 UTC, Roman15122022 commented on src/pages/ServiceMaintenance/index.tsx
> +                  placeholder="Current mileage"
locale

2024-11-26 21:20 UTC, Roman15122022 commented on src/pages/ServiceMaintenance/index.tsx
> +                <h1>Details of service</h1>
same

2024-11-26 21:20 UTC, Roman15122022 commented on src/pages/ServiceMaintenance/index.tsx
> +                <Textarea placeholder="Type your message here." />
same

2024-12-02 20:24 UTC, YaroslavOkrema commented
![image](https://github.com/user-attachments/assets/17445f27-1801-4700-999f-f7d027c2db83)

2024-12-03 19:26 UTC, Roman15122022 approved these changes
In general ok

2024-12-03 19:26 UTC, Roman15122022 commented on src/pages/ServiceMaintenance/useMaintenance.ts
> +}
just return
`locale: translations.maintenance.addMaintenance`

and use it in component
like:
locale.button
locale.cost etc

2024-12-03 19:26 UTC, Roman15122022 commented on src/pages/ServiceMaintenance/index.tsx
> +  } = useMaintenance()
too many elements

2024-12-03 19:26 UTC, Roman15122022 commented on src/pages/ServiceMaintenance/useMaintenance.ts
> +import React from 'react'
for what import React

2024-12-03 19:26 UTC, Roman15122022 commented on src/pages/ServiceMaintenance/index.tsx
> +import React from 'react'
for what import React

2024-12-03 19:31 UTC, Roman15122022 commented on src/pages/ServiceMaintenance/index.tsx
> +                      format(date, 'PPP')
constant for format

2024-12-03 19:31 UTC, Roman15122022 commented on src/pages/ServiceMaintenance/index.tsx
> +                      'w-[240px] justify-start text-left font-normal',
rarely use this constuction [] - tailwind have wonderful size grid

2024-12-09 11:29 UTC, Roman15122022 approved these changes

2024-12-09 13:39 UTC, merged